# Generated by Django 5.2 on 2025-06-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_json',
            field=models.CharField(default='{}', max_length=5000),
            preserve_default=False,
        ),
    ]
